In [4]:
#Mount to your google drive
from google.colab import drive
drive.mount('/content/drive', force_remount= True)

Mounted at /content/drive

In [2]:
import pandas as pd

In [3]:
# working on 'bq_ebitda', and 'bq_ebitda_margin' on all sectors, public companys, and indicators
# company info we need in companies table
company_info= ['bq_sector_name', 'bq_business_code', 'bq_id', 'bq_company_address1_state','bq_public_indicator']

# fileds we need in the company_variables_ts table
company_variables_ts = ['bq_id', 'bq_year']

#Credit risk indicators list
credit_ind_list = ['bq_terminate_any_ind', 'bq_final_filing_any_ind','bq_fail_trans_contrib_pens_ind', 
                 'bq_fail_trans_contrib_welf_ind', 'bq_fail_provide_benf_due_pens_ind', 'bq_fail_provide_benf_due_welf_ind', 
                  'bq_vol_delinquent_filer_pgrm_ind', 'bq_amended_ind','bq_profit_plan_no_co_contribs_ind', 
                  'bq_no_co_contribs_ind', 'bq_no_tot_contribs_ind', 'bq_pens_negative_contrib_ind',	
                  'bq_terminate_pens_ind', 'bq_final_filing_pens_ind',	'bq_no_profit_sharing_ind',
                  'bq_fail_trans_contrib_any_ind', 'bq_fail_provide_benf_due_any_ind']

# Welfare score indicators list
welfare_ind_list = ['bq_health_insurance_ind', 'bq_dental_insurance_ind', 'bq_vision_insurance_ind', 
                  'bq_life_insurance_ind', 'bq_long_term_dis_insurance_ind', 'bq_temp_disability_insurance_ind', 
                  'bq_supp_unemploy_ins_ind', 'bq_death_benefits_ind', 'bq_prepaid_legal_ind', 
                  'bq_scholarship_funded_ind', 'bq_severance_pay_ind', 'bq_apprentice_and_training_ind',
                  'bq_welf_only_ind','bq_welf_ez_only_ind']

# Retirement score indicators list
retirement_ind_list = ['bq_defined_contrib_pens_ind', 'bq_defined_benefit_pens_ind', 'bq_profit_sharing_ind', 
                  'bq_code_section_401k_ind', 'bq_stock_bonus_ind', 'bq_comp_contribute_pens_ind',
                  'bq_target_benefit_plan_ind', 'bq_money_purchase_plan_ind', 'bq_plan_ins_fdlty_bond_ind',
                   'bq_pens_only_ind', 'bq_ez_only_ind']

# Employment & payroll indicators list
payroll_ind_list = ['bq_growth_tot_contrib_per_emp_curr_a_1yr_ind', 'bq_growth_tot_contrib_pens_amt_a_1yr_ind',
                        'bq_growth_co_contrib_pens_amt_a_1yr_ind', 'bq_growth_co_contrib_per_emp_curr_a_1yr_ind',
                        'bq_growth_emp_contrib_pens_amt_a_1yr_ind', 'bq_growth_emp_contrib_per_emp_curr_a_1yr_ind',
                        'bq_growth_revenue_1yr_ind', 'bq_growth_ebitda_1yr_ind', 'bq_growth_cor_1yr_ind',
                        'bq_growth_net_income_1yr_ind', 'bq_growth_gross_profit_1yr_ind', 'bq_growth_total_assets_1yr_ind',
                        'bq_growth_operating_expenses_1yr_ind', 'bq_growth_operating_income_1yr_ind', 
                        'bq_growth_tax_and_interest_1yr_ind', 'bq_growth_revenue_per_emp_1yr_ind',
                        'bq_growth_ebitda_per_emp_1yr_ind', 'bq_growth_cor_per_emp_1yr_ind',
                        'bq_growth_net_income_per_emp_1yr_ind', 'bq_growth_gross_profit_per_emp_1yr_ind',
                        'bq_growth_total_assets_per_emp_1yr_ind', 'bq_growth_operating_expenses_per_emp_1yr_ind',
                        'bq_growth_operating_income_per_emp_1yr_ind', 'bq_growth_tax_and_interest_per_emp_1yr_ind',
                        'bq_growth_savings_score_1yr_ind', 'bq_growth_welfare_score_1yr_ind', 
                        'bq_growth_retirement_score_1yr_ind', 'bq_growth_credit_score_1yr_ind',
                        'bq_growth_benefits_score_1yr_ind', 'bq_growth_smb_default_score_1yr_ind']

# Financial feature list
financials_feature_list = ['bq_revenue', 'bq_ebitda', 'bq_cor', 'bq_net_income', 
                           'bq_gross_profit', 'bq_total_assets','bq_operating_expenses',
                           'bq_operating_income', 'bq_tax_and_interest',
                           'bq_gross_profit_margin', 'bq_ebitda_margin', 'bq_asset_turnover',
                           'bq_net_profit_margin', 'bq_return_on_assets', 'bq_return_on_sales',
                           'bq_revenue_per_emp', 'bq_ebitda_per_emp', 'bq_cor_per_emp',
                           'bq_net_income_per_emp', 'bq_gross_profit_per_emp', 'bq_total_assets_per_emp',
                           'bq_operating_expenses_per_emp', 'bq_operating_income_per_emp', 
                           'bq_tax_and_interest_per_emp']

company_variables_ts_and_features = company_variables_ts + credit_ind_list + welfare_ind_list + retirement_ind_list + payroll_ind_list + financials_feature_list

In [4]:
def feature_selection(dataframe, feature_list):
  '''
    This is a method which returns the new dataframe in which the features are selected
  '''
  return dataframe[feature_list]

In [16]:
# Fetch Raw Data -> Select necessary features by BQ's request -> Save the datasets of Company Variables and Companies to CSVs


company_variables_ts_df1 = feature_selection(pd.read_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data/company_variables_ts_1.csv'), company_variables_ts_and_features)
company_variables_ts_df1.to_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data_state/company_variables_ts_1.csv')

company_variables_ts_df2 = feature_selection(pd.read_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data/company_variables_ts_2.csv'), company_variables_ts_and_features)
company_variables_ts_df2.to_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data_state/company_variables_ts_2.csv')

company_variables_ts_df3 = feature_selection(pd.read_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data/company_variables_ts_3.csv'), company_variables_ts_and_features)
company_variables_ts_df3.to_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data_state/company_variables_ts_3.csv')

company_variables_ts_df4 = feature_selection(pd.read_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data/company_variables_ts_4.csv'), company_variables_ts_and_features)
company_variables_ts_df4.to_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data_state/company_variables_ts_4.csv')

company_variables_ts_df5 = feature_selection(pd.read_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data/company_variables_ts_5.csv'), company_variables_ts_and_features)
company_variables_ts_df5.to_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data_state/company_variables_ts_5.csv')

company_variables_ts_df6 = feature_selection(pd.read_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data/company_variables_ts_6.csv'), company_variables_ts_and_features)
company_variables_ts_df6.to_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data_state/company_variables_ts_6.csv')

company_variables_ts_df7 = feature_selection(pd.read_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data/company_variables_ts_7.csv'), company_variables_ts_and_features)
company_variables_ts_df7.to_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data_state/company_variables_ts_7.csv')

companies_df1 = feature_selection(pd.read_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data/companies_1.csv'), company_info)
companies_df1.to_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data_state/companies_1.csv')

companies_df2 = feature_selection(pd.read_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data/companies_2.csv'), company_info)
companies_df2.to_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data_state/companies_2.csv')

companies_df3 = feature_selection(pd.read_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data/companies_3.csv'), company_info)
companies_df3.to_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data_state/companies_3.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (102) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (58,59,60) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
#Read the company variables datasets and select 2015 - 2020


company_variables_ts_df1 = pd.read_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data_state/company_variables_ts_1.csv')
company_variables_ts_df2 = pd.read_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data_state/company_variables_ts_2.csv')
company_variables_ts_df3 = pd.read_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data_state/company_variables_ts_3.csv')
company_variables_ts_df4 = pd.read_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data_state/company_variables_ts_4.csv')
company_variables_ts_df5 = pd.read_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data_state/company_variables_ts_5.csv')
company_variables_ts_df6 = pd.read_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data_state/company_variables_ts_6.csv')
company_variables_ts_df7 = pd.read_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data_state/company_variables_ts_7.csv')

company_variables_ts_df1 = company_variables_ts_df1[(company_variables_ts_df1.bq_year >= 2015) & (company_variables_ts_df1.bq_year <= 2020)]
company_variables_ts_df2 = company_variables_ts_df2[(company_variables_ts_df2.bq_year >= 2015) & (company_variables_ts_df2.bq_year <= 2020)]
company_variables_ts_df3 = company_variables_ts_df3[(company_variables_ts_df3.bq_year >= 2015) & (company_variables_ts_df3.bq_year <= 2020)]
company_variables_ts_df4 = company_variables_ts_df4[(company_variables_ts_df4.bq_year >= 2015) & (company_variables_ts_df4.bq_year <= 2020)]
company_variables_ts_df5 = company_variables_ts_df5[(company_variables_ts_df5.bq_year >= 2015) & (company_variables_ts_df5.bq_year <= 2020)]
company_variables_ts_df6 = company_variables_ts_df6[(company_variables_ts_df6.bq_year >= 2015) & (company_variables_ts_df6.bq_year <= 2020)]
company_variables_ts_df7 = company_variables_ts_df7[(company_variables_ts_df7.bq_year >= 2015) & (company_variables_ts_df7.bq_year <= 2020)]

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (99) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
#Read the company datasets and select Public Companies


companies_df1 = pd.read_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data_state/companies_1.csv')
companies_df2 = pd.read_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data_state/companies_2.csv')
companies_df3 = pd.read_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data_state/companies_3.csv')

companies_df1 = companies_df1[(companies_df1.bq_public_indicator == 1)]
companies_df2 = companies_df2[(companies_df2.bq_public_indicator == 1)]
companies_df3 = companies_df3[(companies_df3.bq_public_indicator == 1)]

In [7]:
# Combine the 7 company_variables_ts_df dataframes together, Remove new columns that BQ wants to exclude and drop NANs


company_variables_ts_df = pd.concat([company_variables_ts_df1, company_variables_ts_df2, company_variables_ts_df3, company_variables_ts_df4, 
                company_variables_ts_df5, company_variables_ts_df6, company_variables_ts_df7], ignore_index=True)

company_variables_ts_df = company_variables_ts_df.drop([company_variables_ts_df.columns[0]], axis = 1)
company_variables_ts_df.drop("bq_fiscal_year_end", inplace = True, axis = 1)
company_variables_ts_df = company_variables_ts_df.dropna()

In [11]:
# Combine the 3 company_df dataframes together, Remove new columns that BQ wants to exclude and drop NANs


companies_df = pd.concat([companies_df1, companies_df2, companies_df3], ignore_index=True)
companies_df = companies_df.drop([companies_df.columns[0]], axis = 1)
companies_df = companies_df.dropna()

In [14]:
# Save the new processed Companies and Company Variables Datasets


companies_df.to_csv('/content/drive/MyDrive/BrightQuery_Project/Report_Sample_Data/companies_df.csv')
company_variables_ts_df.to_csv('/content/drive/MyDrive/BrightQuery_Project/Report_Sample_Data/company_variables_ts_df.csv')

In [5]:
# Read the saved Companies and Company Variables Datasets, drop unnamed column


companies_df = pd.read_csv('/content/drive/MyDrive/BrightQuery_Project/Report_Sample_Data/companies_df.csv')
companies_df = companies_df.drop([companies_df.columns[0]], axis = 1)

company_variables_ts_df = pd.read_csv('/content/drive/MyDrive/BrightQuery_Project/Report_Sample_Data/company_variables_ts_df.csv')
company_variables_ts_df = company_variables_ts_df.drop([company_variables_ts_df.columns[0]], axis = 1)

In [7]:
# Merge the processed Companies Table and Company Variables Table by company bq id


companies_company_variables = pd.merge(company_variables_ts_df, companies_df, on = "bq_id")

In [ ]:
# Read Statistics Raw Dataset and Table of Statistic fields that BQ wants to investigate, Select the Stats data from 2015-2020
# If stat field's value = NAN then replace it with 0


stats_by_us_ts = pd.read_csv("/content/drive/MyDrive/BrightQuery_Project/Report_Sample_Data/statistics_by_us_ts.csv")

meta_features = pd.read_csv("/content/drive/MyDrive/BrightQuery_Project/Report_Sample_Data/stats_fields")
meta_features = meta_features.drop([meta_features.columns[0]], axis=1) 

selected_meta = ["bq_year"]
selected_meta.extend(list(meta_features["Field name"]))
stats_by_us_ts = stats_by_us_ts[(stats_by_us_ts.bq_year >= 2015) & (stats_by_us_ts.bq_year <= 2020)][selected_meta].fillna(0)

In [10]:
# Save the processed Stats Table


stats_by_us_ts.to_csv('/content/drive/MyDrive/BrightQuery_Project/Report_Sample_Data/stats_fillna.csv')

In [12]:
# Merge the processed Stats Table and Companies + Company Variables Table by year


stats_by_us_ts = pd.read_csv('/content/drive/MyDrive/BrightQuery_Project/Report_Sample_Data/stats_fillna.csv')

merged_meta_data = pd.merge(companies_company_variables, stats_by_us_ts, on = "bq_year")

In [18]:
# Save the merged Companies + Company Variables + Stats as the dataset we want to use


merged_meta_data.sort_values(by=['bq_id','bq_year']).to_csv('/content/drive/MyDrive/BrightQuery_Project/Report_Sample_Data/merged_meta_data.csv')

In [20]:
# Read the processed dataset for Model Training + Evaluation + other processes
# Whole processed dataset

pd.read_csv('/content/drive/MyDrive/BrightQuery_Project/Report_Sample_Data/merged_meta_data.csv',index_col=[0])

           bq_id  ...  bq_total_assets_us_pub_tot
3499   100170449  ...                6.357034e+13
6418   100170449  ...                6.694026e+13
12604  100170449  ...                7.003772e+13
307    100170449  ...                7.167139e+13
15756  100170449  ...                7.663264e+13
...          ...  ...                         ...
8187   999625582  ...                6.694026e+13
14436  999625582  ...                7.003772e+13
2182   999625582  ...                7.167139e+13
17646  999625582  ...                7.663264e+13
11300  999625582  ...                6.169798e+13

[18687 rows x 235 columns]

In [5]:
#Show sample processed dataset (3000)


data = pd.read_csv('/content/drive/MyDrive/BrightQuery_Project/Report_Sample_Data/merged_meta_data.csv',index_col=[0]).head(3000)
#data.to_csv('/content/drive/MyDrive/BrightQuery_Project/Report_Sample_Data/data_3000.csv')
data

           bq_id  ...  bq_total_assets_us_pub_tot
3499   100170449  ...                6.357034e+13
6418   100170449  ...                6.694026e+13
12604  100170449  ...                7.003772e+13
307    100170449  ...                7.167139e+13
15756  100170449  ...                7.663264e+13
...          ...  ...                         ...
5046   253908273  ...                6.357034e+13
8045   253908273  ...                6.694026e+13
14289  253908273  ...                7.003772e+13
2031   253908273  ...                7.167139e+13
17489  253908273  ...                7.663264e+13

[3000 rows x 235 columns]

In [ ]:
#Sample the raw datasets

In [ ]:
#Company Variables Raw Sample


# sample_company_variables = pd.read_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data_state/company_variables_ts_1.csv',index_col=[0]).head(1000)
# sample_company_variables = sample_company_variables.drop([sample_company_variables.columns[-1]], axis = 1)
# sample_company_variables.to_csv('/content/drive/MyDrive/BrightQuery_Project/Report_Sample_Data/company_variables_1000.csv')

In [ ]:
#Companies Raw Sample


# sample_companies = pd.read_csv('/content/drive/MyDrive/BrightQuery_Project/cleaned_data_state/companies_1.csv',index_col=[0]).head(1000)
# sample_companies.to_csv('/content/drive/MyDrive/BrightQuery_Project/Report_Sample_Data/companies_1000.csv')

In [ ]:
#Stats Raw

In [ ]:
# statistics_by_us_ts.csv
# stats_fields.csv